"""Experiment execution and promotion coordination."""

from .budgets import (
    BudgetCrossing,
    BudgetDimension,
    BudgetExceedance,
    BudgetMonitor,
    BudgetUsage,
    causal_training_tokens,
)


from .gates import (
    AmbiguitySnapshot,
    EvidenceBundle,
    GateEngine,
    GateReport,
    GateResult,
    GateResultStatus,
    MaterialChange,
    MetricEvidence,
    PromotionDecision,
    PromotionEngine,
    PromotionRequest,
    PromotionState,
    PromotionStatus,
    RecoveryBudgetState,
    RunGateStateMachine,
    RunGateStatus,
    ScaleValidation,
    snapshot_ambiguities,
)
from .registry import (
    COMPLETE_CHECKPOINT_STATE_KEYS,
    AppendOnlyExperimentRegistry,
    ArtifactAttachment,
    AttemptExecutionContext,
    AttemptRef,
    AttemptStatus,
    AttemptStatusRecord,
    CheckpointPublication,
    ExperimentRef,
    RegistryRecordRef,
    ReproductionOutcome,
    ReproductionProtocol,
    ReproductionValidation,
    ResourceDelta,
    ResourceLedger,
    RunAttempt,
    RunEvent,
    SupersessionRecord,
)
from .journal import FilesystemRegistryJournal
from .store import (
    ArtifactRecoveryReport,
    FilesystemArtifactStore,
    RecoveryIssue,
    RecoveryIssueKind,
)
from .evidence_store import (
    FrozenCorpusBundle,
    RecoveryRunEvidence,
    build_frozen_corpus_bundle,
    build_recovery_run_evidence,
    load_frozen_corpus_bundle,
    load_recovery_run_evidence,
    persist_frozen_corpus_bundle,
    persist_recovery_run_evidence,
)
from .sealing import (
    SealMismatch,
    SealMismatchReason,
    SealedAsset,
    SealedAssetCategory,
    SealedInventory,
    SealVerificationReport,
    allocate_after_seal_verification,
    verify_sealed_inventory,
)



from .ablations import (
    MatchedComparison,
    validate_matched_comparison,
    validate_primary_ablation_suite,
)
from .statistics import (
    PairedCaseDelta,
    PairedStatistics,
    SemanticFamilyDelta,
    confidence_interval,
    exact_enumerated_paired_distribution,
    paired_bootstrap_statistics,
)


from .evaluation import (
    EvaluationBlindStatus,
    EvaluationHistory,
    EvaluationPanel,
    EvaluationPreregistration,
    EvaluationSetPurpose,
    TemporalEvaluationRecord,
    ThresholdSnapshot,
    append_threshold_snapshot,
    record_evaluation_access,
    start_evaluation_history,
)


from .stage1 import (
    REFERENCE_STAGE1_STEPS,
    CausalBatch,
    NoInitializationControl,
    Stage1Checkpoint,
    Stage1ControlComparison,
    Stage1GradientDiagnostics,
    Stage1OptimizerConfig,
    Stage1OptimizerKind,
    Stage1RunResult,
    Stage1RunStatus,
    Stage1TrainerBackend,
    Stage1TrainerConfig,
    causal_language_model_loss,
)
from .transition import (
    AppliedStage1Transition,
    Stage1Transition,
    Stage1TransitionKind,
    apply_stage1_transition,
    build_stage1_transition,
    load_stage1_transition,
    persist_stage1_transition,
)



from .progressive_state import (
    PhaseIndexResolution,
    ProgressiveBoundaryCheckpoint,
    ProgressiveDataCursor,
    ProgressivePhase,
    ProgressivePhasePlan,
    ProgressivePlanKind,
    ProgressiveScheduleState,
    RNGState,
    build_progressive_phase_plan,
    capture_progressive_boundary_checkpoint,
    capture_rng_state,
    load_progressive_checkpoint,
    restore_progressive_checkpoint,
    restore_rng_state,
    save_progressive_checkpoint,
    verify_progressive_checkpoint,
)


from .progressive_trainer import (
    CapabilityEvaluator,
    DistributionMetrics,
    FinalGateEvaluator,
    FinalProgressiveEvidence,
    PhaseGateEvaluator,
    ProgressiveFaultInjector,
    ProgressiveGradientMetrics,
    ProgressiveParameterInventory,
    ProgressiveParameterRecord,
    ProgressivePhaseMetrics,
    ProgressiveRunResult,
    ProgressiveRunStatus,
    ProgressiveTrainerBackend,
    ProgressiveTrainerConfig,
    ProgressiveViewEvaluation,
    ProgressiveViewIdentity,
)
from .progressive_failure import (
    ProgressiveFailureArtifact,
    ProgressiveFailurePoint,
    build_progressive_failure_artifact,
    persist_progressive_failure_artifact,
    verify_progressive_failure_artifact,
)
from .tiny_pipeline import (
    TinyPipelineConfig,
    TinyPipelineInputs,
    TinyPipelineOrchestrator,
    TinyPipelineReportResolver,
    TinyPipelineResult,
    TinyVerticalSliceReport,
)


from .recovery import (
    BinaryActiveForward,
    BinaryForwardEvent,
    LogitSupervisionKind,
    NoProgressDecision,
    NoProgressPolicy,
    RecoveryCorpusMix,
    RecoveryCorpusPlan,
    RecoveryProgressPoint,
    RecoveryRunResult,
    RecoveryRunStatus,
    RecoveryStepEvidence,
    RecoveryTrainerBackend,
    RecoveryTrainerConfig,
    RoutedSupervision,
    SupervisionCoverage,
    SupervisionMode,
    TeacherArtifactStore,
    TeacherIdentity,
    TeacherOutput,
    TeacherPort,
    TeacherRecordProvenance,
    TeacherRole,
    TeacherRouter,
    TeacherRoutingConfig,
    VerifiedTeacherBinding,
    TextLevelEvaluation,
    TextLevelEvaluator,
    TokenMixEvidence,
    TokenMixSliceEvidence,
    aggregate_teacher_weight_artifacts,
    evaluate_no_progress,
    resolve_verified_teacher_binding,
    validate_recovery_token_mix,
)


from .corpus import (
    EMPTY_FROZEN_EVALUATION_DENYLIST,
    EMPTY_PUBLIC_BENCHMARK_DENYLIST,
    INITIAL_TOKEN_ALLOCATION,
    PHASE_COUNT,
    CorpusDenyList,
    CorpusManifest,
    CorpusService,
    DeduplicationReport,
    DuplicateRemoval,
    IsolationExclusion,
    IsolationReport,
    PartitionRef,
    ProvenanceRecord,
    SplitPolicy,
    TokenAllocation,
)


from .evidence_coordinators import (
    BROAD_BENCHMARKS,
    PAPER_ZERO_SHOT_BENCHMARKS,
    RUBRIC_PANELS,
    BlindedRubricPair,
    BroadPanelCoordinator,
    CapabilityCaseResult,
    CapabilityPanelEvidence,
    CapabilityPanelKind,
    CapabilityPanelProtocol,
    CodeCase,
    CodeEvidenceCoordinator,
    CodeExecutionEvidence,
    CodeSubmission,
    DecodingProtocol,
    PairedFailureRecord,
    PairedFailureStatus,
    PaperPanelCoordinator,
    PerplexityCaseResult,
    PerplexityCoordinator,
    PerplexityEvidence,
    PerplexityRun,
    RubricCase,
    RubricEvidence,
    RubricEvidenceCoordinator,
    RubricJudge,
    RubricJudgment,
    RubricPairAudit,
    RubricPreference,
    RubricProtocol,
    SandboxExecutionResult,
    SandboxExecutor,
    SandboxPolicy,
    TokenizationSequenceProtocol,
    coordinate_capability_panel,
    coordinate_perplexity,
)



from .parity import (
    BINARY_OUTPUT_METRIC,
    GREEDY_TOKEN_METRIC,
    LOGIT_METRIC,
    SELECTED_LAYER_METRIC,
    TOOL_DECISION_METRIC,
    NumericalParityStats,
    ParityCoordinator,
    ParityEvidence,
    ParityTrace,
    capture_parity_trace,
)


from .small_scale_protocols import (
    SmallScaleArmKind,
    SmallScalePreflightReport,
    SmallScaleProtocolArm,
    SmallScaleProtocolInputs,
    SmallScaleProtocolKind,
    SmallScaleProtocolSuite,
    allocate_small_scale_model,
    build_small_scale_protocol_suite,
    preflight_small_scale_protocol,
    protocol_catalog,
    validate_serialized_small_scale_suite,
)


from .small_scale_evidence import (
    PrerequisiteEvidence,
    SmallScaleAcceptanceEvidence,
    SmallScaleAcceptanceHarness,
    SmallScaleAcceptanceInputs,
    SmallScaleEvidenceKind,
    SmallScaleEvidenceRecord,
    SmallScalePrerequisite,
)

__all__ = [
    "BudgetCrossing",
    "BudgetDimension",
    "BudgetExceedance",
    "BudgetMonitor",
    "BudgetUsage",
    "causal_training_tokens",
]

__all__ += [
    "AmbiguitySnapshot",
    "EvidenceBundle",
    "GateEngine",
    "GateReport",
    "GateResult",
    "GateResultStatus",
    "MaterialChange",
    "MetricEvidence",
    "PromotionDecision",
    "PromotionEngine",
    "PromotionRequest",
    "PromotionState",
    "PromotionStatus",
    "RecoveryBudgetState",
    "RunGateStateMachine",
    "RunGateStatus",
    "ScaleValidation",
    "snapshot_ambiguities",
    "COMPLETE_CHECKPOINT_STATE_KEYS",
    "AppendOnlyExperimentRegistry",
    "ArtifactAttachment",
    "AttemptExecutionContext",
    "AttemptRef",
    "AttemptStatus",
    "AttemptStatusRecord",
    "CheckpointPublication",
    "ExperimentRef",
    "RegistryRecordRef",
    "ReproductionOutcome",
    "ReproductionProtocol",
    "ReproductionValidation",
    "ResourceDelta",
    "ResourceLedger",
    "RunAttempt",
    "RunEvent",
    "SupersessionRecord",
    "FilesystemRegistryJournal",
    "ArtifactRecoveryReport",
    "FilesystemArtifactStore",
    "RecoveryIssue",
    "RecoveryIssueKind",
    "FrozenCorpusBundle",
    "RecoveryRunEvidence",
    "build_frozen_corpus_bundle",
    "build_recovery_run_evidence",
    "load_frozen_corpus_bundle",
    "load_recovery_run_evidence",
    "persist_frozen_corpus_bundle",
    "persist_recovery_run_evidence",
    "SealMismatch",
    "SealMismatchReason",
    "SealedAsset",
    "SealedAssetCategory",
    "SealedInventory",
    "SealVerificationReport",
    "allocate_after_seal_verification",
    "verify_sealed_inventory",
]

__all__ += [
    "MatchedComparison",
    "validate_matched_comparison",
    "validate_primary_ablation_suite",
    "PairedCaseDelta",
    "PairedStatistics",
    "SemanticFamilyDelta",
    "confidence_interval",
    "exact_enumerated_paired_distribution",
    "paired_bootstrap_statistics",
]

__all__ += [
    "EvaluationBlindStatus",
    "EvaluationHistory",
    "EvaluationPanel",
    "EvaluationPreregistration",
    "EvaluationSetPurpose",
    "TemporalEvaluationRecord",
    "ThresholdSnapshot",
    "append_threshold_snapshot",
    "record_evaluation_access",
    "start_evaluation_history",
]

__all__ += [
    "REFERENCE_STAGE1_STEPS",
    "CausalBatch",
    "NoInitializationControl",
    "Stage1Checkpoint",
    "Stage1ControlComparison",
    "Stage1GradientDiagnostics",
    "Stage1OptimizerConfig",
    "Stage1OptimizerKind",
    "Stage1RunResult",
    "Stage1RunStatus",
    "Stage1TrainerBackend",
    "Stage1TrainerConfig",
    "causal_language_model_loss",
    "AppliedStage1Transition",
    "Stage1Transition",
    "Stage1TransitionKind",
    "apply_stage1_transition",
    "build_stage1_transition",
    "load_stage1_transition",
    "persist_stage1_transition",
]

__all__ += [
    "PhaseIndexResolution",
    "ProgressiveBoundaryCheckpoint",
    "ProgressiveDataCursor",
    "ProgressivePhase",
    "ProgressivePhasePlan",
    "ProgressivePlanKind",
    "ProgressiveScheduleState",
    "RNGState",
    "build_progressive_phase_plan",
    "capture_progressive_boundary_checkpoint",
    "capture_rng_state",
    "load_progressive_checkpoint",
    "restore_progressive_checkpoint",
    "restore_rng_state",
    "save_progressive_checkpoint",
    "verify_progressive_checkpoint",
]

__all__ += [
    "CapabilityEvaluator",
    "DistributionMetrics",
    "FinalGateEvaluator",
    "FinalProgressiveEvidence",
    "PhaseGateEvaluator",
    "ProgressiveFaultInjector",
    "ProgressiveGradientMetrics",
    "ProgressiveParameterInventory",
    "ProgressiveParameterRecord",
    "ProgressivePhaseMetrics",
    "ProgressiveRunResult",
    "ProgressiveRunStatus",
    "ProgressiveTrainerBackend",
    "ProgressiveTrainerConfig",
    "ProgressiveViewEvaluation",
    "ProgressiveViewIdentity",
    "ProgressiveFailureArtifact",
    "ProgressiveFailurePoint",
    "build_progressive_failure_artifact",
    "persist_progressive_failure_artifact",
    "verify_progressive_failure_artifact",
]

__all__ += [
    "TinyPipelineConfig",
    "TinyPipelineInputs",
    "TinyPipelineOrchestrator",
    "TinyPipelineReportResolver",
    "TinyPipelineResult",
    "TinyVerticalSliceReport",
]

__all__ += [
    "BinaryActiveForward",
    "BinaryForwardEvent",
    "LogitSupervisionKind",
    "NoProgressDecision",
    "NoProgressPolicy",
    "RecoveryCorpusMix",
    "RecoveryCorpusPlan",
    "RecoveryProgressPoint",
    "RecoveryRunResult",
    "RecoveryRunStatus",
    "RecoveryStepEvidence",
    "RecoveryTrainerBackend",
    "RecoveryTrainerConfig",
    "RoutedSupervision",
    "SupervisionCoverage",
    "SupervisionMode",
    "TeacherArtifactStore",
    "TeacherIdentity",
    "TeacherOutput",
    "TeacherPort",
    "TeacherRecordProvenance",
    "TeacherRole",
    "TeacherRouter",
    "TeacherRoutingConfig",
    "VerifiedTeacherBinding",
    "TextLevelEvaluation",
    "TextLevelEvaluator",
    "TokenMixEvidence",
    "TokenMixSliceEvidence",
    "aggregate_teacher_weight_artifacts",
    "evaluate_no_progress",
    "resolve_verified_teacher_binding",
    "validate_recovery_token_mix",
]

__all__ += [
    "EMPTY_FROZEN_EVALUATION_DENYLIST",
    "EMPTY_PUBLIC_BENCHMARK_DENYLIST",
    "INITIAL_TOKEN_ALLOCATION",
    "PHASE_COUNT",
    "CorpusDenyList",
    "CorpusManifest",
    "CorpusService",
    "DeduplicationReport",
    "DuplicateRemoval",
    "IsolationExclusion",
    "IsolationReport",
    "PartitionRef",
    "ProvenanceRecord",
    "SplitPolicy",
    "TokenAllocation",
]

__all__ += [
    "BROAD_BENCHMARKS", "PAPER_ZERO_SHOT_BENCHMARKS", "RUBRIC_PANELS",
    "BlindedRubricPair", "BroadPanelCoordinator", "CapabilityCaseResult",
    "CapabilityPanelEvidence", "CapabilityPanelKind", "CapabilityPanelProtocol",
    "CodeCase", "CodeEvidenceCoordinator", "CodeExecutionEvidence", "CodeSubmission",
    "DecodingProtocol", "PairedFailureRecord", "PairedFailureStatus",
    "PaperPanelCoordinator", "PerplexityCaseResult", "PerplexityCoordinator",
    "PerplexityEvidence", "PerplexityRun", "RubricCase", "RubricEvidence",
    "RubricEvidenceCoordinator", "RubricJudge", "RubricJudgment", "RubricPairAudit",
    "RubricPreference", "RubricProtocol", "SandboxExecutionResult", "SandboxExecutor",
    "SandboxPolicy", "TokenizationSequenceProtocol", "coordinate_capability_panel",
    "coordinate_perplexity",
]

__all__ += [
    "BINARY_OUTPUT_METRIC",
    "GREEDY_TOKEN_METRIC",
    "LOGIT_METRIC",
    "SELECTED_LAYER_METRIC",
    "TOOL_DECISION_METRIC",
    "NumericalParityStats",
    "ParityCoordinator",
    "ParityEvidence",
    "ParityTrace",
    "capture_parity_trace",
]

__all__ += [
    "SmallScaleArmKind", "SmallScalePreflightReport", "SmallScaleProtocolArm",
    "SmallScaleProtocolInputs", "SmallScaleProtocolKind", "SmallScaleProtocolSuite",
    "allocate_small_scale_model", "build_small_scale_protocol_suite",
    "preflight_small_scale_protocol", "protocol_catalog",
    "validate_serialized_small_scale_suite",
]

__all__ += [
    "PrerequisiteEvidence", "SmallScaleAcceptanceEvidence",
    "SmallScaleAcceptanceHarness", "SmallScaleAcceptanceInputs",
    "SmallScaleEvidenceKind", "SmallScaleEvidenceRecord",
    "SmallScalePrerequisite",
]
