"""Pure BinaryLLM mathematics."""

from .progressive import (
    OperatorPrecision,
    PAPER_SCHEDULE_RATE,
    PAPER_SCHEDULE_SCALE,
    PhaseIndexConvention,
    ProgressionScheduleConfig,
    ProgressionScheduleKind,
    ProgressiveOperatorConfig,
    REFERENCE_PHASE_COUNT,
    paper_exponential_parameter,
    phase_indices,
    progression_parameters,
    progressive,
    progressive_derivative,
    registered_schedule_kinds,
)
from .scales import (
    AnalyticalScaleGradient,
    DualScaleState,
    FiniteStateDiagnostics,
    InputChannelScale,
    LearnableRowScale,
    NamedTrainableScale,
    ScaleParameterization,
    ScaleRole,
    ScaleTrainabilityReport,
    Stage1Diagnostics,
    Stage1ScaleState,
    TensorFiniteSummary,
    ZeroSignRule,
    analytical_row_scales,
    binary_reconstruction_error,
    binary_sign,
    diagnose_finite_state,
    dual_scaled_sign_weight,
    merged_inference_scales,
    named_trainable_scales,
    scale_trainability_report,
    stage1_diagnostics,
    transformed_weight,
)

__all__ = [
    "AnalyticalScaleGradient", "DualScaleState", "FiniteStateDiagnostics",
    "InputChannelScale", "LearnableRowScale", "NamedTrainableScale", "OperatorPrecision",
    "PAPER_SCHEDULE_RATE", "PAPER_SCHEDULE_SCALE", "PhaseIndexConvention",
    "ProgressionScheduleConfig", "ProgressionScheduleKind", "ProgressiveOperatorConfig",
    "REFERENCE_PHASE_COUNT", "ScaleParameterization", "ScaleRole", "ScaleTrainabilityReport",
    "Stage1Diagnostics", "Stage1ScaleState", "TensorFiniteSummary", "ZeroSignRule",
    "analytical_row_scales", "binary_reconstruction_error", "binary_sign",
    "diagnose_finite_state", "dual_scaled_sign_weight", "merged_inference_scales",
    "named_trainable_scales", "paper_exponential_parameter", "phase_indices",
    "progression_parameters", "progressive", "progressive_derivative",
    "registered_schedule_kinds", "scale_trainability_report", "stage1_diagnostics",
    "transformed_weight",
]
