"""Immutable framework contracts and fail-closed domain validation."""

from .ambiguities import REQUIRED_AMBIGUITY_KEYS, seed_ambiguity_register
from .models import (
    AblationDirection,
    AmbiguityCandidate,
    AmbiguityEntry,
    AmbiguityRegister,
    AmbiguityStatus,
    ArtifactRef,
    BINARY_FAMILY,
    BUILTIN_FAMILIES,
    Budget,
    CandidateRecord,
    CanonicalModel,
    CheckpointBoundary,
    ClaimRecord,
    ClaimStatus,
    ComponentAblationResult,
    DISTILLED_STUDENT_Q4_OR_QAT_FAMILY,
    EvaluationEvidence,
    ExperimentFamilyIdentity,
    ExperimentFamilyKind,
    ExperimentManifest,
    FormatSpec,
    GateCategory,
    GateComparator,
    GateDefinition,
    GateSet,
    ModelIdentity,
    RepresentationKind,
    RepresentationSpec,
    ReproductionAssessment,
    ReproductionClassification,
    ReproductionComponent,
    ReproductionSettings,
    ScaleRung,
    SealedBaselineRef,
    SourceStatus,
    SettingDifference,
    StopMode,
    STRUCTURED_PRUNING_Q4_FAMILY,
    SUPPORTED_SCHEMA_VERSION,
    TERNARY_FAMILY,
    ToleranceDefinition,
    ToleranceSet,
)
from .reproduction import (
    classify_reproduction,
    compare_reproduction_settings,
    release_evidence_for_scale,
    reproduction_setting_difference_paths,
    resolved_settings_from_manifest,
)
from .errors import (
    AmbiguityBlocked,
    ArtifactStoreError,
    BudgetExceeded,
    DeviceQualificationError,
    EvaluationError,
    ExportError,
    FrameworkFailure,
    GateFailure,
    ManifestError,
    NumericalFailure,
    ParityError,
    ProvenanceViolation,
    ReproductionError,
    RegistryJournalError,
    Retryability,
    SealViolation,
)
from .identity import (
    CanonicalDocument,
    ContentIdentity,
    SchemaEvolution,
    evolve_document,
    identify_content,
    new_unique_id,
    sha256_bytes,
)
from .paper import (
    BINARYLLM_PAPER_FACTS,
    BINARYLLM_PAPER_LEDGER,
    BINARYLLM_PAPER_PATH,
    BINARYLLM_PAPER_REFERENCE_SETTINGS,
    BINARYLLM_PAPER_SHA256,
    BINARYLLM_PAPER_TITLE,
    PaperFact,
    PaperFactKind,
    PaperProtocolLedger,
)
from .serialization import (
    CanonicalSerializationError,
    canonical_json,
    canonical_json_bytes,
    parse_canonical_json,
)
from .validation import REQUIRED_FAILURE_GATE_CATEGORIES, validate_candidate, validate_manifest
from .fidelity import (
    BINARYLLM_AMBIGUOUS_PATHS,
    BINARYLLM_FIDELITY_PATHS,
    BinaryLLMFidelityConfig,
    FidelityAblationArm,
    FidelityFieldResolution,
    ProgressiveTrainabilityArm,
    build_binaryllm_reference_config,
    build_matched_fidelity_arms,
)

__all__ = [
    "AblationDirection", "AmbiguityCandidate", "AmbiguityEntry", "AmbiguityRegister", "AmbiguityStatus",
    "ArtifactRef", "BINARY_FAMILY", "BUILTIN_FAMILIES", "Budget", "CandidateRecord",
    "CanonicalModel", "CheckpointBoundary", "ClaimRecord", "ClaimStatus",
    "ComponentAblationResult",
    "DISTILLED_STUDENT_Q4_OR_QAT_FAMILY", "EvaluationEvidence",
    "ExperimentFamilyIdentity", "ExperimentFamilyKind", "ExperimentManifest", "FormatSpec",
    "GateCategory", "GateComparator", "GateDefinition", "GateSet", "ModelIdentity",
    "REQUIRED_AMBIGUITY_KEYS", "REQUIRED_FAILURE_GATE_CATEGORIES", "RepresentationKind",
    "RepresentationSpec", "ReproductionAssessment", "ReproductionClassification",
    "ReproductionComponent", "ReproductionSettings", "SUPPORTED_SCHEMA_VERSION", "STRUCTURED_PRUNING_Q4_FAMILY",
    "ScaleRung", "SealedBaselineRef", "SettingDifference", "SourceStatus", "StopMode",
    "TERNARY_FAMILY",
    "ToleranceDefinition", "ToleranceSet", "classify_reproduction",
    "compare_reproduction_settings", "release_evidence_for_scale",
    "reproduction_setting_difference_paths", "resolved_settings_from_manifest",
    "seed_ambiguity_register", "validate_candidate",
    "validate_manifest", "AmbiguityBlocked", "ArtifactStoreError", "BudgetExceeded", "CanonicalDocument",
    "CanonicalSerializationError", "ContentIdentity", "DeviceQualificationError",
    "EvaluationError", "ExportError", "FrameworkFailure", "GateFailure", "ManifestError",
    "NumericalFailure", "ParityError", "ProvenanceViolation", "ReproductionError",
    "RegistryJournalError",
    "Retryability", "SchemaEvolution", "SealViolation", "canonical_json",
    "canonical_json_bytes", "evolve_document", "identify_content", "new_unique_id",
    "parse_canonical_json", "sha256_bytes",
    "BINARYLLM_PAPER_FACTS", "BINARYLLM_PAPER_LEDGER",
    "BINARYLLM_PAPER_PATH", "BINARYLLM_PAPER_REFERENCE_SETTINGS",
    "BINARYLLM_PAPER_SHA256", "BINARYLLM_PAPER_TITLE",
    "PaperFact", "PaperFactKind", "PaperProtocolLedger",
    "BINARYLLM_AMBIGUOUS_PATHS", "BINARYLLM_FIDELITY_PATHS",
    "BinaryLLMFidelityConfig", "FidelityAblationArm",
    "FidelityFieldResolution", "build_binaryllm_reference_config",
    "ProgressiveTrainabilityArm", "build_matched_fidelity_arms",
]


from .ablations import (
    PAIRED_BOOTSTRAP_RESAMPLES,
    PAIRED_CONFIDENCE_LEVEL,
    REQUIRED_PRIMARY_ABLATION_FACTORS,
    AblationArm,
    AblationClassification,
    AblationDefinition,
    BootstrapPlan,
    ScoreObservation,
)

__all__ += [
    "PAIRED_BOOTSTRAP_RESAMPLES",
    "PAIRED_CONFIDENCE_LEVEL",
    "REQUIRED_PRIMARY_ABLATION_FACTORS",
    "AblationArm",
    "AblationClassification",
    "AblationDefinition",
    "BootstrapPlan",
    "ScoreObservation",
]
